#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"TrainingPortal"}),expects="1+"
#@overlay/match-child-defaults missing_ok=True
---
spec:
  portal:
    #@ if/end data.values.index:
    index: #@ data.values.index
