#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ def secretcopier(name, ns_from, ns_to):
#@ if ns_from != ns_to:
kind: SecretCopier
apiVersion: secrets.educates.dev/v1beta1
metadata:
  name: #@ "{}-{}".format(name, ns_to)
spec:
  rules:
    - reclaimPolicy: Delete
      sourceSecret:
        name: #@ name
        namespace: #@ ns_from
      targetNamespaces:
        nameSelector:
          matchNames:
            -  #@ ns_to
#@ end
#@ end

#@ if data.values.mode == "app_per_bundle":

#@ for bundle in data.values.workshop_bundles:

#@ if hasattr(bundle.credentials, "secretRef") and hasattr(bundle.credentials.secretRef, "namespace"):
#@ if bundle.credentials.secretRef.namespace != None:
--- #@ secretcopier(bundle.credentials.secretRef.name, bundle.credentials.secretRef.namespace, "workshops-{}".format(bundle.name))
#@ end
#@ end

#@ if hasattr(data.values.overlays.credentials, "secretRef") and hasattr(data.values.overlays.credentials.secretRef, "namespace"):
#@ if data.values.overlays.credentials.secretRef.namespace != None:
--- #@ secretcopier(data.values.overlays.credentials.secretRef.name, data.values.overlays.credentials.secretRef.namespace, "workshops-{}".format(bundle.name))
#@ end
#@ end

#@ if hasattr(data.values.config.credentials, "secretRef") and hasattr(data.values.config.credentials.secretRef, "namespace"):
#@ if data.values.config.credentials.secretRef.namespace != None:
--- #@ secretcopier(data.values.config.credentials.secretRef.name, data.values.config.credentials.secretRef.namespace, "workshops-{}".format(bundle.name))
#@ end
#@ end

#@ if hasattr(data.values.common_credentials, "secretRef") and hasattr(data.values.common_credentials.secretRef, "namespace"):
#@ if data.values.common_credentials.secretRef.namespace != None:
--- #@ secretcopier(data.values.common_credentials.secretRef.name, data.values.common_credentials.secretRef.namespace, "workshops-{}".format(bundle.name))
#@ end
#@ end

#@ end

#@ else:

#@ for bundle in data.values.workshop_bundles:

#@ if hasattr(bundle.credentials, "secretRef") and hasattr(bundle.credentials.secretRef, "namespace"):
#@ if bundle.credentials.secretRef.namespace != None:
--- #@ secretcopier(bundle.credentials.secretRef.name, bundle.credentials.secretRef.namespace, "workshops-{}".format("global"))
#@ end
#@ end

#@ end

#@ if hasattr(data.values.overlays.credentials, "secretRef") and hasattr(data.values.overlays.credentials.secretRef, "namespace"):
#@ if data.values.overlays.credentials.secretRef.namespace != None:
--- #@ secretcopier(data.values.overlays.credentials.secretRef.name, data.values.overlays.credentials.secretRef.namespace, "workshops-{}".format("global"))
#@ end
#@ end

#@ if hasattr(data.values.config.credentials, "secretRef") and hasattr(data.values.config.credentials.secretRef, "namespace"):
#@ if data.values.config.credentials.secretRef.namespace != None:
--- #@ secretcopier(data.values.config.credentials.secretRef.name, data.values.config.credentials.secretRef.namespace, "workshops-{}".format("global"))
#@ end
#@ end

#@ if hasattr(data.values.common_credentials, "secretRef") and hasattr(data.values.common_credentials.secretRef, "namespace"):
#@ if data.values.common_credentials.secretRef.namespace != None:
--- #@ secretcopier(data.values.common_credentials.secretRef.name, data.values.common_credentials.secretRef.namespace, "workshops-{}".format("global"))
#@ end
#@ end

#@ end
